import type { Metadata } from "next";

import { Cairo, DM_Sans } from "next/font/google";

// import { FormProvider } from "@/context/FormContext";

import { Toaster } from "react-hot-toast";

import "./globals.css";

const cairo = Cairo({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`${cairo.className} min-h-screen h-screen overflow-y-auto w-screen overflow-x-hidden`}>
          {children}
          <Toaster position="bottom-right" />
        </div>
      </body>
    </html>
  );
}