import type { Metadata } from "next";

import { Cairo, DM_Sans } from "next/font/google";

// import { FormProvider } from "@/context/FormContext";

import { Toaster } from "react-hot-toast";

import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";

const cairo = Cairo({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!h-full !text-[13px] lg:!text-[16px]">
      <body className="!h-full">
        {/* h-full to not take the height of the browser's toolbar */}
        {/* NextUIProvider used to allow using nextUI individual components */}
        <NextUIProvider className={`${cairo.className} h-full overflow-y-auto w-screen overflow-x-hidden`}>
              {children}
            <Toaster position="bottom-right" />
        </NextUIProvider>
      </body>
    </html>
  );
}